### ISSUE TITLE
Match major version in search

### ISSUE THREAD

**Issue by j0lol** [ryanccn/moddermore#13]
Some fabric/quilt mods don't label minor versions because they're interchangeable in most cases. Maybe add options for version matching. (like polymc)

**Comment by ryanccn** [comment]
https://github.com/PolyMC/PolyMC/issues/1031 mod updater doesn't have it yet lol

yeah that's probably a good idea

**Comment by ryanccn** [comment]
uwu

https://github.com/ryanccn/moddermore/commit/d052e8bc5c4dd5fa2f8a5826412beeb5a52f3e75
