### ISSUE TITLE
[BUG] CurseForge-Only Mods Not Downloading

### ISSUE THREAD

**Issue by UnperishedDev** [ryanccn/moddermore#133]
**Describe the bug**
Exporting CurseForge mods as a .zip archive fails to work.

**To Reproduce**
1. Add any CurseForge-only mod to a moddermore list.
2. Attempt to export the list to a .zip archive
3. View the error

**Expected behavior**
I expected to be able to download the mods as normal.

**Screenshots**
<img width="541" alt="Screenshot 2023-05-21 at 5 23 42 PM" src="https://github.com/ryanccn/moddermore/assets/131722267/5b49f238-28a6-4551-b51b-f129cec7f9cd">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3
 - Browser: Safari
 - Version: Latest

**Comment by ryanccn** [comment]
Can't replicate, could you DM me the link to the actual list? `RyanCaoDev#0428`

**Comment by UnperishedDev** [comment]
No discord.

Can you view the list [here](https://gist.github.com/UnperishedDev/8e79a8a71349c12983bc54cd6e6ee9a3)?

**Comment by ryanccn** [comment]
That's not the list, I mean the actual list on the website <img src="https://cdn.discordapp.com/emojis/1103650070441775124.webp?size=32&quality=lossless" width="16" height="16" alt="pain">

**Comment by UnperishedDev** [comment]
Here it is (actually lol):  https://moddermore.net/list/K2w5_HB5xRpP

**Comment by ryanccn** [comment]
Fixed in https://github.com/ryanccn/moddermore/commit/011d317d600aac0bfc7b55d7b217c29c4b7936e1
