### ISSUE TITLE
Specify mod version

### ISSUE THREAD

**Issue by otomir23** [ryanccn/moddermore#139]
**Is your feature request related to a problem? Please describe.**
Sometimes latest versions of mods aren't compatible with each other or some fixes rolled out as a alpha/beta release, but moddermore downloads latest stable release.

**Describe the solution you'd like**
Allow user to specify a version of the mod (includeing versions marked as aplha/beta/pre-release).

**Comment by ryanccn** [comment]
Done! https://moddermore.net/changelog/2023-08-27-version-pinning
