### ISSUE TITLE
Problem exporting to MCC launcher

### ISSUE THREAD

**Issue by SeaSide53** [ryanccn/moddermore#150]
**The issue**
When you export to the latest version of MCC (both with packwiz and without) it tells you you need to use the OneSix instance format.

**My fix**
Just adding `InstanceType=OneSix` to the top of my instance.cfg fixed everything for me.

**Screenshots**
![image](https://github.com/ryanccn/moddermore/assets/125594629/e931d38c-52d0-483b-b361-5a31ffa39be7)

**Comment by ryanccn** [comment]
Thanks for the report!
