### ISSUE TITLE
Packwiz curseforge mods

### ISSUE THREAD

**Issue by LittleLigr** [ryanccn/moddermore#166]
**Issue**
So, I don't clearly understand, is it bug or not, but....
If I try to export mod list in packwiz - mods that hosted on curseforge not included in index.toml

**To Reproduce**
Open any mod list, that contains mods from CurseForge and try to find them.

**Comment by vgskye** [comment]
could not reproduce with https://moddermore.net/list/7foVTHnm3DIk
