### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by MisileLab** [ryanccn/moddermore#167]
**Is your feature request related to a problem? Please describe.**
I want make a new cli app that uses moddermore api, but it's not documented and i can't use it

**Describe the solution you'd like**
Can you make api and also access key(api key)?

**Describe alternatives you've considered**
Idk

**Additional context**

**Comment by ryanccn** [comment]
Currently there's no such thing as an API key, although I suppose you *could* try to use the NextAuth APIs to obtain a token? I can put this on my to-do list but its not going to be the highest priority
