### ISSUE TITLE
[Bug] Export frozen for everything besides zip

### ISSUE THREAD

**Issue by DatCaptainHorse** [ryanccn/moddermore#185]
**Describe the bug**
Trying to use the website for first time, spent some time making a basic base modpack, tried to export with every non-zip option, seems each one freezes up.

**To Reproduce**
1. Go to `https://moddermore.net/list/wfeAa0_hBfYn`
2. Export as any non-zip option (i.e. Modrinth)
3. Open console, see error listed 

**Expected behavior**
Modpack to export

**Screenshots**
![image](https://github.com/ryanccn/moddermore/assets/14197772/6192ce75-3e2a-42ed-965b-62afc5467fd4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Chromium
 - Version: 116

**Additional context**
Here's a snack :cookie:

**Comment by ryanccn** [comment]
Seems like a bug with Forge version resolution 😮‍💨
