### ISSUE TITLE
Moddermore seems to be broken for me 

### ISSUE THREAD

**Issue by deventity** [ryanccn/moddermore#207]
**Describe the bug**
For me, none of the authentication methods do work, and the mods list can not be fetched

**To Reproduce**
1. Go to moddermore.net
2. Try to sign any using any of the available options

**Expected behavior**
The sign in should be successful and the mod lists should be shown.

**Screenshots**

![Screenshot_9](https://github.com/ryanccn/moddermore/assets/33573453/a68c69a3-f709-4adf-8c1c-c64e0563d0a0)
![Screenshot_8](https://github.com/ryanccn/moddermore/assets/33573453/ab30ad8a-7a12-49a4-9935-43b220a46bb3)
![Screenshot_8](https://github.com/ryanccn/moddermore/assets/33573453/253ce005-8e4c-45f0-998a-be6eda1895a3)

**Desktop (please complete the following information):**

- OS: Windows 10 Professional  22H2
- Browser Microsoft Edge
- Version 117.0.2045.43

**Additional context**
If I try to sign in using the magic link, every link is seen as invalid for some reason.
The only sign in method that works is discord, but as soon as the login process is finished the mods can not be resolved and the whole applications stales.

I've tried several things:
 - Clearing the browser cache
 - Deleting all cookies 
 - Allowing third party cookies
 - Run it on a fresh OS instance inside Windows Sandbox

**Comment by ryanccn** [comment]
Fixed.
