### ISSUE TITLE
Selected versions don't get set in exported Packwiz

### ISSUE THREAD

**Issue by RealArmenium** [ryanccn/moddermore#237]
**Describe the bug**
If a mod has multiple versions that you can select from, and you select a version that is not the most recent version, the exported Packwiz doesn't seem to be acknowledging that that previous version was selected. I initially thought that this might be an issue with Packwiz, but after seeing #213 being reported, I think that it may just be because the selected version is not properly being provided to Packwiz.

**To Reproduce**

1. Go to any modpack
2. Click "Edit"
3. Select a version for a mod that is not the most recent version available in the dropdown
4. Click "Save"
5. Export as MultiMC (auto-updating)
6. Import in PolyMC/MultiMC/Prism Launcher and run the instance.
7. Check if version for the mod matches with the one listed in Moddermore.

**Expected behavior**

**Screenshots**
The Sodium version I have selected is 0.4.10:
![image](https://github.com/ryanccn/moddermore/assets/53126710/3e0184c9-9697-4a87-bc29-fee191556a51)

However, the version being downloaded by Packwiz is 0.5.3:
![image](https://github.com/ryanccn/moddermore/assets/53126710/b458827a-3699-45ba-9c92-7e5c050656fd)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Google Chrome
- Launcher: Prism Launcher 7.2

**Comment by ryanccn** [comment]
Apologies for the late response, I was busy
