### ISSUE TITLE
Support additional login methods

### ISSUE THREAD

**Issue by JJTech0130** [ryanccn/moddermore#25]
It would be great to support additional login methods, as magic links can be annoying. My email reader automatically fetches the contents of URLs to generate metadata, and this makes the link expire. And I can't login on devices without access to my email.

**Comment by ryanccn** [comment]
Yes, I find magic links annoying sometimes as well...

The issue is `next-auth` does not support automatic account linking, so for each sign-in method you will have a different account. That can feel weird in certain cases because you can't link accounts together unlike on some other platforms.

**Comment by ryanccn** [comment]
Done!
