### ISSUE TITLE
Wrong forge version when exporting to MultiMC

### ISSUE THREAD

**Issue by MrNaru300** [ryanccn/moddermore#269]
**Describe the bug**
The minecraft runs without loading the forge mod loader because the forge version is wrong.

**To Reproduce**
1. Create a Forge modpack in recent versions (1.19.2 in my case)
2. Export the modpack for MultiMC (either normal or auto-updating)
3. Import as a zip in MultiMC
4. Start instance
5. Minecraft opens without loading Forge

**Screenshots**

![image](https://github.com/ryanccn/moddermore/assets/33036217/45a73f2f-bd53-42da-8203-518c9095c73f)
![image](https://github.com/ryanccn/moddermore/assets/33036217/d29d41d0-819e-4b67-aabb-04e49d2eaf3f)

- forge version should be 43.3.5 but it's 1.19.2-43.3.5

**Comment by ryanccn** [comment]
Thank you for reporting this issue!
