### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by allanonmage** [ryanccn/moddermore#299]
**Describe the bug**
Can't be clear, I'm browsing your site for the first time using Waterfox and Vivaldi.  I can't see much, and searching for "5" (random number) gives me nothing (Waterfox), or a little popup that says I'm being rate limited (Vivaldi)

**Expected behavior**
I'm a new user, so I'm trying to figure out what your site does and how it works and if it will solve my problem.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser Waterfox (current), Vivaldi

**Additional context**
I don't have Discord because they have never let me use my account in the ~10 years that I've had it.  So here I am.

**Comment by ryanccn** [comment]
A very small amount of lists have opted in to being available in search, that's why there are so few results; you might be better off searching with actual words.

The rate limit is a feature to prevent spamming the search endpoint.

**Comment by allanonmage** [comment]
oh, ok.  I did a search for Sodium and got some results.  PLaying around with it now.
