### ISSUE TITLE
Some mods are not find-able when I try to add them into a pack

### ISSUE THREAD

**Issue by allanonmage** [ryanccn/moddermore#300]
**Describe the bug**
I went through a list of mods yesterday and made a modpack.  Or tried to.  I'm not done, but I found 13 mods that were indeed listed on Modrinth or Curseforge, and were indeed version-compatible with what I made the list with.  But Moddermore could not find them.  I used Waterfox (Firefox based) and Vivaldi (chrome based).  They are the latest versions, or maybe 1 behind.

In a couple of cases, it seemed that the developer had a different name for their name vs the name in the URL, so I was able to find the mods that way.  However, I didn't notice that same phenomenon for these mods.

```
Horse Expert	https://modrinth.com/mod/horse-expert
ThonkUtil	https://www.curseforge.com/minecraft/mc-mods/thonkutil/
More Villagers	https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric
Everything is Copper	https://modrinth.com/mod/everythingcopper/
Netherite Plus Mod	https://modrinth.com/mod/netherite-plus-mod
Map Shirts	https://modrinth.com/mod/map-shirts
Pesky Seagulls	https://modrinth.com/mod/pesky-seagulls
Map Album	https://modrinth.com/mod/map-album
Fast Async World Save	https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric
Queen Bee	https://modrinth.com/mod/queen-bee/gallery
Paintings with Dragons	https://www.curseforge.com/minecraft/mc-mods/paintings-with-dragons
Breezy	https://modrinth.com/mod/breezy/
Storage Labels	https://www.modrinth.com/mod/labels

```

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Waterfox, Vivaldi

Pack that I'm working on: https://moddermore.net/list/2eX8EjJqfNKG

**Comment by ryanccn** [comment]
A lot of the mods you're trying to add are for Forge. Your list is for Fabric.
