### ISSUE TITLE
Packwiz export support

### ISSUE THREAD

**Issue by ryanccn** [ryanccn/moddermore#9]
Add [packwiz](https://packwiz.infra.link/) support so that lists can be directly imported into [`packwiz-installer`](https://packwiz.infra.link/tutorials/installing/packwiz-installer/), making it convenient for auto-updating clients ~~(even on MultiMC)~~ and servers.

Main pain points will be the problem of pinning specific mods to versions, and the hashes needed to provide to packwiz-compatible clients. Possibly will need to fetch every single mod TOML from the pack TOML serverless function. Not 
ideal

## Links

- https://packwiz.infra.link/reference/pack-format/pack-toml/
- https://packwiz.infra.link/reference/pack-format/index-toml/
- https://packwiz.infra.link/reference/pack-format/mod-toml/

**Comment by ryanccn** [comment]
Although Vercel Pro plan *does* provide 60 seconds of runtime, and we don't really use serverless functions for anything other 
than the cursed proxy...

**Comment by AshtakaOOf** [comment]
August 8 2022 :skull:
