### ISSUE TITLE
Exporting CurseForge download links in .mrpack

### ISSUE THREAD

**Issue by Scubakay** [ryanccn/moddermore#91]
**Is your feature request related to a problem? Please describe.**
I just created a modpack using Moddermore for the first time. I really like the way it works, but there's one issue that makes exporting .mrpack kinda inferior to just using Export and getting a zip of all the mods. When downloading an .mrpack it doesn't include CurseForge mods that I added in the pack.

Looking at mrpack.ts I see that this was done deliberately (or it hasn't been implemented yet):

```
urls.filter(
    (dl) => !('error' in dl) && dl.provider === 'modrinth'
 )
 ```

**Describe the solution you'd like**
Support for CurseForge mods in the mrpack exports.

**Describe alternatives you've considered**
An alternative to this is to manually add the CurseForge download links to the json file in the mrpack. I tried this with ReplayMod and it did work when I created a new MultiMC instance with it.

**Comment by ryanccn** [comment]
That's an issue a lot of people have been running into, thanks for taking the time to report it!

The main reason I currently exclude CurseForge mods from any `mrpack` export is that CurseForge does not allow modpacks uploaded to Modrinth to include download links to their CDN. However, usage for importing to launchers probably falls out of this scope...

I think what I will probably do is an option at export time to choose whether you want to bundle in CurseForge mods (requiring users to check if these mods allow redistribution), include their download links (making them ineligible for publishing to Modrinth), or just skip them.

**Comment by Scubakay** [comment]
I thought it might have to do with CurseForge whining about Modrinth, but yeah not every mrpack will be uploaded to Modrinth. Also, does Modrinth actually check if there's CurseForge links in the mrpacks?

**Comment by ryanccn** [comment]
> Also, does Modrinth actually check if there's CurseForge links in the mrpacks?

Yes, I think there's validation that prevents modpacks with CurseForge CDN links from being uploaded

**Comment by ryanccn** [comment]
> Also, does Modrinth actually check if there's CurseForge links in the mrpacks?

Yes, I think there's validation that prevents modpacks with CurseForge CDN links from being uploaded
