### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by Pokethorix** [ryanccn/moddermore#92]
**Is your feature request related to a problem? Please describe.**
It's pretty annoying when you select all the mods you want and when you start up minecraft, it crashes and
sometimes doesn't even give you the name of the mod that crashed it, so you have to look through every mod page to
find which mod could be outdated or incompatible with another mod.

**Describe the solution you'd like**
Any mods that don't support the version selected on the modpack could be highlighted in red and moved to the top of the list,
along with text stating the latest version of the mod.
If a mod is incompatible with another mod or requires a dependency, the mods needed to be added or deleted will be listed
in the mod window.

**Additional context**
Mods could also be layed out in rows of 3 instead of 1 long list down the middle of the screen, especially for some of the larger
modpacks.

ALSO I realise that a point made here, dependency, has already been suggested in a previous enhancement. My bad.

**Comment by ryanccn** [comment]
Good ideas, I'll take a look at solving these issues when I get the time!

**Comment by Pokethorix** [comment]
Alright thanks :)
